site_name: Object Synchronizer for PUN

# Documentation and theme
theme:
  name: 'material'
  custom_dir: 'theme'
  palette:
    primary: 'magenta'
    accent: 'light blue'

extra_css:
  - stylesheets/dark_theme.css
  - stylesheets/codehilite.css

markdown_extensions:
  - admonition
  - codehilite

pages:
  - Getting started: 'index.md'
  - Allowed types: 'Allowed-types.md'
  - The SyncList: 'SyncList.md'
  - Supporting your own types: 'supporting-your-own-types.md'
  - Data optimization: 'Data-optimization.md'
  - FAQ: 'FAQ.md'